# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 187a5ade3b40d1381a18cf8c7ab83e84af373effdc9c3f1d84e26e26c669a6f031d24d45103c64b4fc11a252ccf109141b7d591eab1314399fb9dd0acdb4d531

test:
  secret_key_base: 73cbafe5118cc8f8a58f0f981851e2d10c23c5b4580550f59781f9857df842e589a251084cd6713b01583521edbcae956fb75cc7f082371180c32f9260151858

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
